# Generated by Django 4.1.7 on 2023-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarticle',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
