# Generated by Django 4.1.7 on 2023-03-20 21:13

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='media/course_images')),
                ('level', models.CharField(choices=[('Beginner', 'Boshlang`ich'), ('Intermediate', 'O`rtacha'), ('Advanced', 'Qo`shimcha')], default='Beginner', max_length=30)),
                ('description', ckeditor.fields.RichTextField()),
                ('demo_video', models.FileField(upload_to='')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('language', models.CharField(max_length=60)),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chegirmadagi narxi')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70)),
                ('description', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib nomeri')),
                ('lesson_status', models.CharField(choices=[('Not seen', 'Ko`rilmagan'), ('In progress', 'Jarayonda'), ('Reviewed', 'Ko`rilgan'), ('Not purchased', 'Sotib olinmagan')], default="Ko'rilmagan", max_length=40)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Course',
                'verbose_name_plural': 'Purchase Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('video', models.FileField(upload_to='')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Video uzunligi ozi yozadi yozmasangiz  bo'ladi", max_digits=100, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('useful_files', models.FileField(blank=True, null=True, upload_to='media/useful_materials')),
                ('useful_links', models.URLField(blank=True, null=True)),
                ('useful_images', models.ImageField(blank=True, null=True, upload_to='media/useful_materials')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courselesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Completed',
                'verbose_name_plural': 'Courses Completed',
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecompleted')),
            ],
            options={
                'verbose_name': 'Course Comment',
                'verbose_name_plural': 'Courses Comments',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursecategory'),
        ),
    ]
