# Generated by Django 4.1.7 on 2023-03-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
