# Generated by Django 4.1.7 on 2023-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=255)),
                ('win_percent', models.FloatField()),
                ('games_played', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Player',
            },
        ),
    ]
