# Generated by Django 4.1.7 on 2023-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_games_played_player_blitz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chess Rating',
                'verbose_name_plural': 'Chess Rating',
            },
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
