# Generated by Django 4.1.7 on 2023-03-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chessrating_delete_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessRating',
        ),
    ]
